### ISSUE TITLE
Recurring events don't show up in upcoming events widget

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Sugar-Event-Calendar#48]
Events that recur do not get displayed in the upcoming events widget (or archive) except for their very first instance.

**Comment by pippinsplugins** [comment]
I've just pushed a bunch of formatting fixes to `issue/48`. @growdev please review the changes; that's the formatting standard that should be used.

How's the archive view coming?

**Comment by growdev** [comment]
I've opened #72 so I can clean up formatting globally when the release is ready to go.

For the archive view, would the correct approach be to hook into `pre_get_posts` on the archive page and add the recurring events to the results?

**Comment by growdev** [comment]
I'm re-stating the tasks for this issue below so I can track if they are complete:

- [ ] Recurring events do not get displayed in the upcoming events widget 
- [ ] The widget should show:
	1. All events
	2. Upcoming events
	3. Past events events
- [ ] Show recurring events in archive view

**Comment by growdev** [comment]
I've got the widgets cleaned up.  Added `sc_get_all_events()` which calculates an array keyed off start timestamp for all events. Example:

```

**Comment by growdev** [comment]
@pippinsplugins I still need some feedback on how to affect the archive view.

**Comment by pippinsplugins** [comment]
>>>For the archive view, would the correct approach be to hook into pre_get_posts on the archive page and add the recurring events to the results?

Yes.

**Comment by growdev** [comment]
@pippinsplugins I'm at a loss on how to use `pre_get_posts` on the archive page. 

`pre_get_posts` will modify the query, but we need to get the timestamps out of the post meta and sort it. 

This is what is happening in [sc_get_all_events()](https://github.com/pippinsplugins/Sugar-Event-Calendar/blob/issue/48/includes/functions.php#L1503).

Is there a way to say "This is an archive view so use this list of posts (returned from sc_get_all_events()) instead of the query results" ?

**Comment by pippinsplugins** [comment]
I think you'd need to hook into `pre_get_posts`, perform a look up with `sc_get_all_events()`, extract the post IDs, then set `post__in`. Essentially duplicating the queries.

Let's go ahead and punt the archive view so we can get this finished up.

**Comment by growdev** [comment]
I could hug you, thanks! This was bending my brain.

**Comment by pippinsplugins** [comment]
:heart:

**Comment by growdev** [comment]
This is ready to test.  :tada:

You will need to open + save all of your recurring events so that the `sc_all_recurring` meta is added. 

For customers this will be handled in the upgrades.php where `sc_update_recurring_events()` will be called.


Here's an upcoming events widget:
![screen shot 2017-02-23 at 11 01 25 pm](https://cloud.githubusercontent.com/assets/290886/23291176/0765335c-fa1c-11e6-8b04-e1544b782cf8.png)


Here is a past events widget only for events in category 'Social':
![screen shot 2017-02-23 at 11 02 43 pm](https://cloud.githubusercontent.com/assets/290886/23291188/345b422a-fa1c-11e6-98c5-46ca32d66851.png)


Here's an 'All' events widget which starts at the first occurring event:
![screen shot 2017-02-23 at 11 03 36 pm](https://cloud.githubusercontent.com/assets/290886/23291205/54c2256a-fa1c-11e6-9716-a977271c69e9.png)

**Comment by pippinsplugins** [comment]
@growdev I'd prefer to test this with the full upgrade routine to ensure my tests work the same way that customers' will. Is that ready to go?

**Comment by growdev** [comment]
@pippinsplugins  Yes, the current `upgrades.php` should handle updating.

**Comment by pippinsplugins** [comment]
@growdev I'm getting a fatal error on the calendar now in `issue/48`:

Fatal error: Uncaught Error: Call to undefined function sc_get_events_for_day() in /Users/pippin/Sites/edd/wp-content/plugins/sugar-calendar/includes/functions.php:93 Stack trace: #0 /Users/pippin/Sites/edd/wp-content/plugins/sugar-calendar/includes/functions.php(184): sc_draw_calendar('3', '2017', 'small', 0) #1 /Users/pippin/Sites/edd/wp-content/plugins/sugar-calendar/includes/calendar.php(106): sc_draw_calendar_month(1488923702, 'small', 0) #2 /Users/pippin/Sites/edd/wp-content/plugins/sugar-calendar/includes/widgets.php(46): sc_get_events_calendar('small', 0) #3 /Users/pippin/Sites/edd/wp-includes/class-wp-widget.php(395): sc_events_widget->widget(Array, Array) #4 /Users/pippin/Sites/edd/wp-includes/widgets.php(738): WP_Widget->display_callback(Array, Array) #5 /Users/pippin/Sites/edd/wp-content/themes/twentysixteen/sidebar.php(13): dynamic_sidebar('sidebar-1') #6 /Users/pippin/Sites/edd/wp-includes/template.php(684): require_once('/Users/pippin/S...') #7 /Users/pippin/Sites/edd/wp-includes/template.php(643): load_tem in /Users/pippin/Sites/edd/wp-content/plugins/sugar-calendar/includes/functions.php on line 93

**Comment by growdev** [comment]
@pippinsplugins fixed!  I removed some functions when fixing merge conflicts from #60.

This pr should be working now.

**Comment by growdev** [comment]
Closing this as #60 was merged.
