### ISSUE TITLE
Order of recurring events not correct or consistent

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/Sugar-Event-Calendar#52]
Recurring events should be displayed on the calendar in the same order each time they occur and also in chronological order.

See this image for an illustration of the current issue:
<img width="1273" alt="screen-shot-2016-01-18-at-10-44-08-pm" src="https://cloud.githubusercontent.com/assets/1034109/12410574/8c812528-bedb-11e5-9374-d9f63dcd92a4.png">

**Comment by pippinsplugins** [comment]
@growdev I have two recurring events, one that starts at 7pm and one that starts at 10pm.

The 10pm event is shown first but should be shown second.

Can you test and replicate?

**Comment by growdev** [comment]
Yes, replicated. Here a recurring Dinner (8pm-10pm) is showing before a recurring Breakfast (7am-9am)

![screen shot 2017-02-02 at 11 04 28 am](https://cloud.githubusercontent.com/assets/290886/22559644/64b744e6-e937-11e6-9370-9775a69aaf6f.png)

This is because the routine to calculate and add recurring events to the display isn't sorted by start time like single events. 

I'm working this morning on this.

**Comment by growdev** [comment]
Okay, I have this displaying correctly. Also refactored how the events are pulled together before they are displayed.
![screen shot 2017-02-02 at 12 14 39 pm](https://cloud.githubusercontent.com/assets/290886/22562227/407172fa-e941-11e6-94ed-e2be2af38af9.png)

**Comment by growdev** [comment]
@pippinsplugins ready for review.

**Comment by pippinsplugins** [comment]
@growdev this looks good, except it broke the `Recur Until` option. Events are now recurring forever even if an end date is set.

**Comment by pippinsplugins** [comment]
Related #73

**Comment by growdev** [comment]
Recur Until is fixed now.

**Comment by pippinsplugins** [comment]
Looks good now!
